config/routes.rb
RR::Application.routes.draw do

  resources :availabilities

  resources :divisions
  match "/divisions/dex_up/:id/" => "divisions#dex_up"
  resources :forums
  match "/forums/dex_up/:id/" => "forums#dex_up" 
  resources :topics  
  resources :posts
  match "posts/:id/toggle_publish" => "posts#toggle_publish"
  
  resources :users
  match "users/:action/:id" => "users#:action"
  
  resources :authentications, :only => [:index, :create, :destroy]
  
  match '/auth/:service/callback', :to => 'authentications#auth_callback' 
  match '/auth/failure',           :to => 'authentications#failure'  
  match "/authenticate",           :to => "authentications#authenticate"
  match "/signout",                :to => "authentications#signout"
  
  match "/register",         :to => "users#new"
  
  
  root :to => 'pages#root'
  
  match "/about",            :to => "pages#about"
  match "/about_ruin_rails", :to => "pages#about_ruin_rails"
  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :title, :dex, :division_id
  
  belongs_to :division
  has_many :topics, :dependent => :destroy
    
  validates :dex, :presence => true, :numericality => { :only_integer => true }
  validates :division_id, :presence => true, :numericality => { :only_integer => true }
  validates :title, :length => { :maximum => 100 },
                    :presence => true
                    
  def swap_dex_with(forum)
    forum.dex, self.dex = self.dex, forum.dex
    forum.save
    self.save
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  
  before_filter :authenticate, :only => [ :index, :new, :create, :show, :edit, :update, :destroy ]
  before_filter :admin_auth, :only => [ :index, :new, :create, :edit, :update, :destroy, :dex_up ]
  
  def new
    @division = Division.find(params[:division_id])
    @title = "#{@division.title}/Forums/new"
    @forum = Forum.new
  end

  def create
    @title = "#{Division.find(params[:division_id]).title}/Forums/new"
    @forum = Forum.new(:title => params[:forum][:title], 
                      :dex => new_forum_dex_for_div(params[:division_id]), 
                      :division_id => params[:division_id])
    @division = @forum.division
    if params[:commit] == "Cancel"
      redirect_to divisions_path
    else
      if @forum.save
        flash[:success] = "Forum, #{@forum.title} created successfully!"
        redirect_to divisions_path
      else
        flash[:error] = "Error in forum creation process!"
        render 'new'
      end
    end
  end

  def show
    @forum = Forum.find(params[:id])
    redirect_to divisinos_path unless user_has_clearance?(@forum.division.read_level)
    @topics = @forum.topics.by_updated
    @title = "#{@forum.division.title}/#{@forum.title}"
  end

  def edit
    @forum = Forum.find(params[:id])
    @title = "#{@forum.division.title}/#{@forum.title}/edit"
  end

  def update
    @forum = Forum.find(params[:id])
    @title = "#{@forum.division.title}/#{@forum.title}/edit"
    
    if params[:commit] == "Cancel"
      redirect_to forum_path(@forum.id)
    else
      if @forum.update_attributes(params[:forum])
        flash[:success] = "Forum updated successfully."
        redirect_to forum_path(@forum.id)
      else
        flash[:error] = "Forum update failed."
        redirect_to forum_path(@forum.id)
      end
    end
  end

  def destroy
    begin
      Forum.find(params[:id]).destroy
      flash[:success] = "Forum destroyed"
    rescue
      flash[:error] = "Forum destruction unsuccessful"
    ensure
      redirect_to divisions_path
    end
  end
  
  private
    def new_forum_dex_for_div(div_id)
      dex = Forum.find_all_by_division_id(div_id).count
    end

end

app/views/forums/edit.html.erb
<%= link_to "/Divisions", divisions_path %> <%= link_to "/#{@forum.division.title}", division_path(@forum.division.id)%>
<%= form_for(@forum) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title, :autofocus => true %>
	</div>
	<div class="field">
		<%= f.label "Division ID" %><br />
		<%= f.text_field :division_id %>
	</div>
	<div class="actions">
		<%= f.submit "Confirm Editions", :class => "action" %>
		<%= f.submit "Cancel", :class => "action" %>
	</div>
<% end %>

<table>
	<tr><th>ID:</th><th>Title</th></tr>
	<% Division.all.each do |d| %>
		<tr>
			<td><%= d.id %></td><td><%= d.title%></td>
		</tr>
	<% end %>
</table>

app/views/forums/new.html.erb
<%= link_to "/Divisions", divisions_path %> <%= link_to "/#{@division.title}", division_path(@division.id)%>
<%= form_for(@forum) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title, :autofocus => true %>
	</div>
	<%= hidden_field_tag(:division_id, params[:division_id]) %>
	<div class="actions">
		<%= f.submit "Create Forum", :class => "action" %>
		<%= f.submit "Cancel", :class => "action" %>
	</div>
<% end %>

app/views/forums/show.html.erb
<%= link_to "/Divisions", divisions_path %> <%= link_to "/#{@forum.division.title}", division_path(@forum.division.id)%>
<div class="list">
	<h3 class="title">
		<sup><%= @forum.id if admin? %> <%= @forum.dex if admin? %></sup>
		<%= @forum.title %>			
		<sup><%= link_to "X", @forum, 	:method => :delete,
						  	  				:confirm => "Forum and all child forums will be permanently and irrecoverably destroyed!  Are you sure?",
						  	  				:title => "Delete #{@forum.title}",
						  	  				:class => "destroy button",
						  	  				:title => "Destroy" if admin? %></sup>
		<sup><%= link_to "E", edit_forum_path(@forum.id), :class => "edit button", :title => "Edit" if admin? %></sup>
	</h3>

	<table>
		<% @topics.each do |t| %>
			<tr class="item">
				<td id="item"><%= link_to topic_path(t.id), :class => "item" do %><%= t.title %> <sub><%= t.posts.publish.count %></sub><% end %></td>
				<td class="new emph"><%= "<--- Updated #{distance_of_time_in_words_to_now(t.updated_at)} ago" if t.updated_at > current_user.last_login %></td>
				<td class="thin"><nobr><%= link_to "-#{t.user.name}", user_path(t.user.id), :class => "user" %></nobr></td>
				<td class="thin"><nobr><%= "#{distance_of_time_in_words_to_now(t.created_at)} ago" %></nobr></td>
			</tr>
		<% end %>
	</table>
	
	<%= link_to "+Topic", new_topic_path(:forum_id => @forum.id), :class => "add_item", :title => "Create New Topic" if current_user.rank.clearance >= @forum.division.write_level%>
</div>