config/routes.rb
RR::Application.routes.draw do

  resources :availabilities

  resources :divisions
  match "/divisions/dex_up/:id/" => "divisions#dex_up"
  resources :forums
  match "/forums/dex_up/:id/" => "forums#dex_up" 
  resources :topics  
  resources :posts
  match "posts/:id/toggle_publish" => "posts#toggle_publish"
  
  resources :users
  match "users/:action/:id" => "users#:action"
  
  resources :authentications, :only => [:index, :create, :destroy]
  
  match '/auth/:service/callback', :to => 'authentications#auth_callback' 
  match '/auth/failure',           :to => 'authentications#failure'  
  match "/authenticate",           :to => "authentications#authenticate"
  match "/signout",                :to => "authentications#signout"
  
  match "/register",         :to => "users#new"
  
  
  root :to => 'pages#root'
  
  match "/about",            :to => "pages#about"
  match "/about_ruin_rails", :to => "pages#about_ruin_rails"
  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :forum_id
  
  belongs_to :forum
  belongs_to :user
  has_many :posts, :dependent => :destroy

  validates :forum_id, :numericality => { :only_integer => true },
                       :presence => true
  
  validates :user_id, :numericality => { :only_integer => true },
                      :presence => true
  validates :title, :length => { :maximum => 50 },
                    :presence => true
  scope :by_updated, order("updated_at DESC")
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate, :only => [ :index, :new, :create, :show, :edit, :update, :destroy ]
  before_filter :admin_auth, :only => [ :destroy ]
  
  def new
    @topic = Topic.new
    @forum = Forum.find params[:forum_id]
    @title = "#{@forum.division.title}/#{@forum.title}/Topics/new"
    
    return redirect_to forum_path(@forum.id) unless user_has_clearance?(@forum.division.write_level)
  end
  
  def create
      @topic = Topic.new(:title     => params[:topic][:title],                    
                         :forum_id  => params[:forum_id])
      @topic.user_id = current_user.id
      @forum = @topic.forum
      @title = "#{@forum.division.title}/#{@forum.title}/Topics/new"
      
      return redirect_to forum_path(@topic.forum.id) unless user_has_clearance?(@topic.forum.division.write_level)
    if params[:commit] == "Cancel"
      redirect_to forum_path(params[:forum_id])
    else
      if @topic.save
        flash[:success] = "Topic, #{@topic.title} created successfully!"
        redirect_to topic_path(@topic.id)
      else
        flash[:error] = "Error in topics creation process!"
        render 'new'
      end
    end
  end

  def show
    @topic = Topic.find(params[:id])
    return redirect_to divisions_path unless user_has_clearance?(@topic.forum.division.read_level)
    if admin?
      @posts = Post.ordered.in_topic(@topic).page(params[:page]).per(25)
    else
      @posts = Post.ordered.in_topic.published_or_belongs_to(current_user.id).page(params[:page]).per(25)
    end
    @post = Post.new
    @title = "#{@topic.forum.division.title}/#{@topic.forum.title}/#{@topic.title}"
  end

  def edit
    @topic = Topic.find(params[:id])
    return redirect_to divisions_path unless user_has_clearance?(@topic.forum.division.write_level)
    @title = "#{@topic.forum.division.title}/#{@topic.forum.title}/#{@topic.title}/edit"
  end

  def update
    @topic = Topic.find(params[:id])
    return redirect_to divisions_path unless user_has_clearance?(@topic.forum.division.read_level)

    if params[:commit] == "Cancel"
      redirect_to forum_path(@topic.forum_id)
    else
      if @topic.update_attributes(params[:topic])
        flash[:success] = "Topic updated successfully."
        redirect_to forum_path(@topic.forum_id)
      else
        flash[:error] = "Topic update failed."
        render edit_topic(params[:id])
      end
    end
  end
  

  def destroy
    begin
      @topic = Topic.find(params[:id])
      forum_id = @topic.forum_id
      @topic.destroy
      flash[:success] = "Topic destroyed"
    rescue
      flash[:error] = "Topic destruction unsuccessful"
    ensure
      redirect_to forum_path, :id => forum_id
    end
  end
  
  def publish_post(post)
    return true if post.publish
    return true if admin?
    return true if post.user == current_user
    return false
  end
end

app/views/topics/edit.html.erb
<%= link_to "Forums", divisions_path %>
<%= form_for(@topic) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title, :autofocus => true %>
	</div>
	<%= hidden_field_tag(:forum_id, params[:forum_id]) %>
	<div class="actions">
		<%= f.submit "Confirm Editions", :class => "action" %>
		<%= f.submit "Cancel", :class => "action" %>
	</div>
<% end %>

app/views/topics/new.html.erb
<%= link_to "/Divisions", divisions_path %>
<%= link_to "/#{@forum.division.title}", division_path(@forum.division.id)%>
<%= link_to "/#{@forum.title}", forum_path(@forum.id) %>
<%= form_for(@topic) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title, :autofocus => true %>
	</div>
	<%= hidden_field_tag(:forum_id, params[:forum_id]) %>
	<div class="actions">
		<%= f.submit "Create Topic", :class => "action" %>
		<%= f.submit "Cancel", :class => "action" %>
	</div>
<% end %>

app/views/topics/show.html.erb
<%= link_to "/Divisions", divisions_path %> <%= link_to "/#{@topic.forum.division.title}", division_path(@topic.forum.division.id)%>  <%= link_to "/#{@topic.forum.title}", forum_path(@topic.forum.id) %>
<div class="list">	
	<h3 class="title">
		<sup><%= @topic.id if admin? %></sup>
		<%= @topic.title %>			
		<sup><%= link_to "X", @topic, 	:method => :delete,
						  	  				:confirm => "Topic and all child posts will be permanently and irrecoverably destroyed!  Are you sure?",
						  	  				:title => "Delete #{@topic.title}",
						  	  				:class => "destroy button",
						  	  				:title => "Destroy" if admin? %></sup>
		<sup><%= link_to "E", edit_topic_path(@topic.id), :class => "edit button", :title => "Edit" if admin? %></sup>
	</h3>
	<%= paginate @posts %>	
	<table>
		<%= render :partial => '/shared/post', :collection => @posts %>
	</table>
	<%= paginate @posts %>	
	<div class="add_item"><%= link_to "+Post", new_post_path(:topic_id => @topic.id), :class => "add_item", :tilte => "Create New Topic"  if current_user.rank.clearance >= @topic.forum.division.write_level %></div>
</div>
<% if current_user.rank.clearance >= @topic.forum.division.write_level %>
	<%= form_for(@post) do |p| %>
		<%= render 'shared/error_messages', :object => p.object %>
		<div class="field">
			<%= p.label :content %><br />
			<%= p.text_area :content %>
		</div>
	<div class="de-emph" id="note">(HTML enabled)</div>
		<%= hidden_field_tag(:topic_id, @topic.id) %>
		<div class="actions">
			<%= p.submit "Create Post", :class => "action" %>
			<%= p.submit "Preview Post", :class => "action" %>
			<%= p.submit "Cancel", :class => "action" %>
		</div>
	<% end %>
<% end %>