config/routes.rb
RR::Application.routes.draw do

  resources :availabilities

  resources :divisions
  match "/divisions/dex_up/:id/" => "divisions#dex_up"
  resources :forums
  match "/forums/dex_up/:id/" => "forums#dex_up" 
  resources :topics  
  resources :posts
  match "posts/:id/toggle_publish" => "posts#toggle_publish"
  
  resources :users
  match "users/:action/:id" => "users#:action"
  
  resources :authentications, :only => [:index, :create, :destroy]
  
  match '/auth/:service/callback', :to => 'authentications#auth_callback' 
  match '/auth/failure',           :to => 'authentications#failure'  
  match "/authenticate",           :to => "authentications#authenticate"
  match "/signout",                :to => "authentications#signout"
  
  match "/register",         :to => "users#new"
  
  
  root :to => 'pages#root'
  
  match "/about",            :to => "pages#about"
  match "/about_ruin_rails", :to => "pages#about_ruin_rails"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :downcase_email
  
  has_many :authentications, :dependent => :destroy
  has_many :topics
  has_many :posts
  has_many :availabilities, :dependent => :destroy
  
  belongs_to :rank
  
  attr_accessible :name, :email, :time_zone
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  user_regex = /^\w+$/
  
  validates :name, :presence => true,
                   :format   => { :with => user_regex, :message => "Only letters, numbers and underscores allowed." },
                   :length   => { :maximum => 50 }
           
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :time_zone, :presence   => true

  scope :by_name, order('name ASC')
  scope :by_date, order('created_on ASC')

  def fake_name
    Faker::Name.name
  end
  
  private
    def downcase_email
      self.email.downcase!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :not_signed_in, :only => [:new, :create]
  before_filter :admin_auth, :only => [ :promote, :demote ]
  
  def fake_name
    Faker::Name.name
  end
  
  def index
    @title = "users"
    @users = User.by_name
  end
  
  def new
    @title = "register"
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
  end
  
  def create
    if params[:commit] == "Cancel"
      session[:authhash] = nil
      session.delete :authhash
      redirect_to root_url
      flash[:notice] = "Registration Aborted."
    else
        
      @user = User.new(params[:user])
      @user.rank = Rank.find_by_title("Registered")
      if @user.save
        auth = @user.authentications.create!(:provider => params[:provider],
                                      :uid      => params[:uid],
                                      :uname    => params[:uname],
                                      :uemail   => params[:uemail])
        create_session(auth)
        flash[:success] = "Account created successfully!"
        #redirect_to @user
        redirect_to :action => "show", :controller => "users", :id => auth.user.id
      else
        flash[:error] = "There were problems during registration.  Account not created!"
        render 'new'
      end
    end
  end
  
  def edit
    if admin?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    @title = "users/#{@user.name}/edit"
  end
  
  def update
    @user = User.find(params[:id])
    
    if params[:commit] == "Cancel"
        flash[:notice] = "User update canceled."
    else
      if @user.update_attributes(params[:user])
        flash[:success] = "User updated successfully."
      else
        flash[:error] = "User update failed."
      end
    end
      redirect_to user_path(@user.id)
  end
  
  def not_signed_in
    unless !signed_in?
      flash[:error] = "You are already authenticated and registered!  Log out if you wish to register another acount."
      redirect_to root_path
    end
    
  end
    
  def show
    @user = User.find(params[:id])
    @title = User.find(params[:id]).name
    @availabilities = Availability.for_user(@user).by_begin
  end
  
  def promote
    @user = User.find(params[:id])
    if @rank = Rank.find_by_clearance(@user.rank.clearance + 1)
      @user.rank = @rank
      @user.save
    else
      flash[:error] = "Cannot promote any further"
    end
    redirect_to users_path
  end
  
  def demote
    @user = User.find(params[:id])
    if @rank = Rank.find_by_clearance(@user.rank.clearance - 1)
      @user.rank = @rank
      @user.save
    else
      flash[:error] = "Cannot demote any further!"
    end
    redirect_to users_path
  end
end

app/views/users/_user_availabilities.html.erb
<div class="list">
	<h3>Availability</h3>
	<table>
		<% @availabilities.each do |a| %>
		<tr>
			<td><span class="de-emph">From:</span> <%= a.begin.strftime('%A %l:%M %p') %></td>
			<td><span class="de-emph">Until:</span> <%= a.end.strftime('%A %l:%M %p') %></td>
			<td><%= link_to "X", a, :method => :delete, :class => "destroy button", :title => "Delete Availability" if admin? || a.user == current_user %></td>
		</tr>
		<% end %> 
	</table>
	<%= link_to "Add Availability", new_availability_path, :class => "cool_link" if @user == current_user %>
</div>

app/views/users/_user_info.html.erb
<div class="list">
	<h3>Information</h3>
	<ul>
		<li>Name: <%= @user.name %></li>
		<% if signed_in? && @user.id == current_user.id %>
			<li>Email: <%= @user.email %> <span class="emph">(hidden)</span></li>
		<% end %>
		<li>Access Rank: <%= @user.rank.title %></li>
		<li>Local Timezone: <%= @user.time_zone %></li>
		<li><%= "Member Since: #{@user.created_at.strftime('%B %d, %Y')}" %></li>
	</ul>
	<% if signed_in? && @user.id == current_user.id %>
		<%= link_to "Edit Account", edit_user_path(params[:id]), :class => "cool_link" %>
	<% end %>
</div>

app/views/users/create.html.erb


<ul>
	<% request.env.each do |item| %>
	    <li><%= item[0] %> : <%= item[1] %></li>
	<% end %>
</ul>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :timezone %>
		<%= f.time_zone_select :time_zone %>
	</div>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="actions">
		<%= f.submit "Confirm Editions", :class => "action" %>
		<%= f.submit "Cancel", :class => "action" %>
	</div>
<% end %>

app/views/users/index.html.erb

<% if signed_in? %>
	<div class="mini_nav"><%= link_to "Availabilities", availabilities_path %></div>
<% end %>

<table>
	<tr>
		<th>Name</th>
		<th><nobr>Member Since</nobr></th>
		<th><nobr>Access Rank</nobr></th>
	</tr>
	<% @users.each do |u| %>
		<tr>
			<td><%= link_to u.name, :action => "show", :controller => "users", :id => u.id %></td>
			<td><%= "#{u.created_at.strftime('%B %d, %Y')}" %></td>
			<td class="thin"><%= u.rank.title %></td>
			<% if signed_in? 
				if admin? %>
				<td class="thin"><%= link_to "^", { :controller => "users", :action => "promote", :id => u.id }, :class => "button", :title => "Promote" %></td>
				<td class="thin"><%= link_to "v", { :controller => "users", :action => "demote", :id => u.id }, :class => "button", :title => "Promote" %></td>
			<% end
			end %>
		</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :timezone %>
		<%= f.time_zone_select :time_zone %>
	</div>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %><h4>This name will represent you everywhere on the site.</h4>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %><h4>A valid email is required to confirm identity and retrieve a lost account.</h4>
	</div>
	<%= hidden_field_tag :uid, params[:uid] %> 
	<%= hidden_field_tag :uname, params[:uname] %>
	<%= hidden_field_tag :uemail, params[:uemail] %>
	<%= hidden_field_tag :provider, params[:provider] %>
	<div class="actions">
		<%= f.submit "Register New Account", :class => "action" %>
		<%= f.submit "Cancel", :class => "action" %>
	</div>
<% end %>

app/views/users/show.html.erb
<% if @user.rank.clearance == 0 %>
	<h2>IMPORTANT!</h2>
	<h4>Your access rank is "Registered" - an admin has been notified and will promote you appropriately.</h4>
	<h4>You may view the <%= link_to "public forums", divisions_path %> until then.</h4>
<% end %>

<%= render 'user_info' %>
<%= render 'user_availabilities' %>