config/routes.rb
RR::Application.routes.draw do

  resources :availabilities

  resources :divisions
  match "/divisions/dex_up/:id/" => "divisions#dex_up"
  resources :forums
  match "/forums/dex_up/:id/" => "forums#dex_up" 
  resources :topics  
  resources :posts
  match "posts/:id/toggle_publish" => "posts#toggle_publish"
  
  resources :users
  match "users/:action/:id" => "users#:action"
  
  resources :authentications, :only => [:index, :create, :destroy]
  
  match '/auth/:service/callback', :to => 'authentications#auth_callback' 
  match '/auth/failure',           :to => 'authentications#failure'  
  match "/authenticate",           :to => "authentications#authenticate"
  match "/signout",                :to => "authentications#signout"
  
  match "/register",         :to => "users#new"
  
  
  root :to => 'pages#root'
  
  match "/about",            :to => "pages#about"
  match "/about_ruin_rails", :to => "pages#about_ruin_rails"
  

end

app/views/layouts/_footer.html.erb
<footer class="round">
	<%= link_to "Ruin_Rails", about_ruin_rails_path %>
</footer>

app/views/layouts/_header.html.erb
<header>
	<table>
		<tr>
			<td id="logo"><h1><%= link_to logo, root_path, :id => "logo" %></h1></td>
			<td id="site">
				<%= link_to "About", about_path %>
				<%= link_to "Forums", divisions_path %>
				<%= link_to "Users", users_path %></td>
			</td>
			<td id="account">
				<% if signed_in? %>
					<%= current_user.name %> (<%= current_user.rank.title %>)
					<%= link_to "Profile", :action => "show", :controller => "users", :id => current_user.id %>
					<nobr><%= link_to "Sign Out", "/signout" %></nobr>
				<% else %>
					<nobr><%= link_to "Sign In/Register", "/authenticate" %></nobr>
				<% end %>
			</td>
		</tr>
	</table>
</header>

app/views/layouts/_links.html.erb
<%= link_to "about", about_path %>
<%= link_to "users", users_path %>

app/views/layouts/_scheme.html.erb
<table id="scheme">
	<tr>
		<td id="scheme-0">111111</td>
		<td id="scheme-1">1a1a1a</td>
		<td id="scheme-2">4d4d4d</td>
		<td id="scheme-3">878787</td>
		<td id="scheme-4">bababa</td>
		<td id="scheme-5">e0e0e0</td>
		<td id="scheme-6">ffffff</td>
		<td id="scheme-7">fddbc7</td>
		<td id="scheme-8">f4a582</td>
		<td id="scheme-9">d6604d</td>
		<td id="scheme-10">b2182b</td>
		<td id="scheme-11">67001f</td>
		<td id="scheme-12">4575b4</td>
		<td id="scheme-13">74add1</td>
		<td id="scheme-14">abd9e9</td>
		<td id="scheme-15">e0f3f8</td>
	</tr>
</table>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'application', :media => 'screen' %>
<%= javascript_include_tag "application" %>
<link href='http://fonts.googleapis.com/css?family=Contrail+One|Atomic+Age|Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>

app/views/layouts/_testing.html.erb
<%= debug(params) if Rails.env.development? %>
<ul>
	<% request.env.each do |item| %>
	    <li><%= item[0] %> : <%= item[1] %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= title %></title>
	  <%= render "layouts/stylesheets"%>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tag %>
	</head>
	<body>
		<% if signed_in? %>
			<% if current_user.rank.clearance == 0 %>
				<% flash.now[:notice] = "Notice! Your access rank is 'Registered'; you do not have posting privileges until an admin has approved your account." %>
			<% end %>
		<% end %>
		<%= render 'layouts/header' %>
		<div class="container">
	        <% flash.each do |key, value| %>
	            <div class="flash <%= key %> round"><%= value %></div>
	        <% end %>
			<section>
				<h1>/<%= @title %></h1>
			    <%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= render "layouts/testing" if Rails.env.development? and true %>
		</div>
	</body>
</html>